global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'bfa-go'
    static_configs:
      - targets: ['bfa-go:8080']

  - job_name: 'agent-python'
    static_configs:
      - targets: ['agent-python:8000']